package com.jfinal.app.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBlog<M extends BaseBlog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}
	
	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}
	
	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}
	
	/**
	 * 文章配图
	 */
	public void setPic(java.lang.String pic) {
		set("pic", pic);
	}
	
	/**
	 * 文章配图
	 */
	public java.lang.String getPic() {
		return getStr("pic");
	}
	
	/**
	 * 0为草稿，1为发布
	 */
	public void setState(java.lang.Integer state) {
		set("state", state);
	}
	
	/**
	 * 0为草稿，1为发布
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}
	
	public void setSeoKeywords(java.lang.Integer seoKeywords) {
		set("seoKeywords", seoKeywords);
	}
	
	public java.lang.Integer getSeoKeywords() {
		return getInt("seoKeywords");
	}
	
	public void setSeoDescription(java.lang.Integer seoDescription) {
		set("seoDescription", seoDescription);
	}
	
	public java.lang.Integer getSeoDescription() {
		return getInt("seoDescription");
	}
	
	/**
	 * 浏览量
	 */
	public void setViewCount(java.lang.Integer viewCount) {
		set("viewCount", viewCount);
	}
	
	/**
	 * 浏览量
	 */
	public java.lang.Integer getViewCount() {
		return getInt("viewCount");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreated() {
		return getDate("created");
	}
	
	/**
	 * 最后更新时间
	 */
	public void setUpdated(java.util.Date updated) {
		set("updated", updated);
	}
	
	/**
	 * 最后更新时间
	 */
	public java.util.Date getUpdated() {
		return getDate("updated");
	}
	
}

