package com.jfinal.app.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSession<M extends BaseSession<M>> extends Model<M> implements IBean {

	/**
	 * session id
	 */
	public void setId(java.lang.String id) {
		set("id", id);
	}
	
	/**
	 * session id
	 */
	public java.lang.String getId() {
		return getStr("id");
	}
	
	/**
	 * 账户 id
	 */
	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	/**
	 * 账户 id
	 */
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreated() {
		return getDate("created");
	}
	
	/**
	 * 过期时间
	 */
	public void setExpires(java.util.Date expires) {
		set("expires", expires);
	}
	
	/**
	 * 过期时间
	 */
	public java.util.Date getExpires() {
		return getDate("expires");
	}
	
}

