package com.jfinal.app.blog.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseImage<M extends BaseImage<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}
	
	/**
	 * 上传者
	 */
	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	/**
	 * 上传者
	 */
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}
	
	/**
	 * 相对于jfinal baseUploadPath 的相对路径
	 */
	public void setPath(java.lang.String path) {
		set("path", path);
	}
	
	/**
	 * 相对于jfinal baseUploadPath 的相对路径
	 */
	public java.lang.String getPath() {
		return getStr("path");
	}
	
	/**
	 * 文件名
	 */
	public void setFileName(java.lang.String fileName) {
		set("fileName", fileName);
	}
	
	/**
	 * 文件名
	 */
	public java.lang.String getFileName() {
		return getStr("fileName");
	}
	
	/**
	 * 显示名
	 */
	public void setShowName(java.lang.String showName) {
		set("showName", showName);
	}
	
	/**
	 * 显示名
	 */
	public java.lang.String getShowName() {
		return getStr("showName");
	}
	
	/**
	 * 文件长度
	 */
	public void setLength(java.lang.Integer length) {
		set("length", length);
	}
	
	/**
	 * 文件长度
	 */
	public java.lang.Integer getLength() {
		return getInt("length");
	}
	
	/**
	 * 创建时间
	 */
	public void setCreated(java.util.Date created) {
		set("created", created);
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreated() {
		return getDate("created");
	}
	
}

