package com.jfinal.app.blog.common.model;

import com.jfinal.app.blog.common.model.base.BaseImage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Image extends BaseImage<Image> {
	
}
