package com.jfinal.app.blog.common.model;

import com.jfinal.app.blog.common.model.base.BaseSession;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Session extends BaseSession<Session> {
	
}
